### ISSUE TITLE
ERROR_API_NOT_AVAILABLE

### ISSUE THREAD

**Issue by blairjo** [abitofsoftware/capacitor-check-app-update#1]
Hi, 

Thanks for creating this plugin, it should save me a ton of time! I just tried it out by running from android studio, but I get the above error. I've spent a while on google, and I *think* that this plugin will only work if you do the initial install from the play store. 

Can you confirm that is the case please - I suspected at first that it might be an android version thing, but [this link](https://medium.com/google-developer-experts/exploring-in-app-updates-on-android-57f1aee011cb) says that it is available from 21 upwards, which is my minimum version. 

Thanks!

**Comment by MarnickvdA** [comment]
Hi @blairjo,

First of all, thank you for using the plugin and issuing this ticket! 

I have looked into the problem that you are facing and I have experienced the same error. My idea behind this plugin is to only use this plugin for builds for the App and Play Store. I haven't added functionality to test the plugin in your development environment (yet). 

Android's documentation states that you could test this functionality before going live with your app by [internal app sharing](https://support.google.com/googleplay/android-developer/answer/9303479). 

I will update the README to give more information about the workings of this plugin.

I hope this (temporary) solution suits your needs and don't hesitate to issue another ticket if something is still not working!

Kind regards,

Marnick

**Comment by blairjo** [comment]
Hi, 

Just an update on this - the plugin is working fine now that I had a version installed properly via the app store. 

One other issue I had
